defaults: &defaults
  working_directory: &working_directory
    /go/src/github.com/influxdata/telegraf

deps-images: &deps-images
  docker:
    - image: 'quay.io/influxdb/telegraf-ci:1.11.5'

godep_cache_key: &godep_cache_key v1-vendor-{{ checksum "Gopkg.lock" }}
restore_godep_cache: &restore_godep_cache
  restore_cache:
    key: *godep_cache_key

checkout_cache_key: &checkout_cache_key v1-repo-{{ .Environment.CIRCLE_SHA1 }}
restore_checkout_cache: &restore_checkout_cache
  restore_cache:
    key: *checkout_cache_key

git-submodule: &git-submodule
  run: 
    name: Sync submodule
    command: |
      git submodule sync --recursive
      git submodule update --recursive --init
---
defaults:
  defaults: &defaults
    working_directory: '/go/src/github.com/influxdata/telegraf'
  go-1_9: &go-1_9
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.9.7'
  go-1_10: &go-1_10
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.10.8'
  go-1_11: &go-1_11
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.11.5'

version: 2

jobs:
  deps:
    <<: [*defaults, *deps-images]
    steps:
      - checkout
      - save_cache:
          key: *checkout_cache_key
          paths: *working_directory      
      - *restore_godep_cache
      - *git-submodule
      - run: 'make deps'
      - save_cache: 
          key: *godep_cache_key
          paths:
            - "./vendor"
      - persist_to_workspace:
          root: '/go/src'
          paths:
            - '*'

  test:
    <<: [*defaults, *deps-images]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make test'
      - run: 
          name: Build test
          command: |
            CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o build/telegraf cmd/telegraf/telegraf.go
      # disabled due to gofmt differences (1.10 vs 1.11).
      #- run: 'make check'
      - run: 'make test'
  test-go-1.10:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      # disabled due to gofmt differences (1.10 vs 1.11).
      #- run: 'make check'
      - run: 'make test'
  test-go-1.11:
    <<: [ *defaults, *go-1_11 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make check'
      - run: 'make test'
  test-go-1.11-386:
    <<: [ *defaults, *go-1_11 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'GOARCH=386 make check'
      - run: 'GOARCH=386 make test'

  package:
    <<: [ *defaults, *go-1_11 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make package'
      - store_artifacts:
          path: './build'
          destination: 'build'
  release:
    <<: [*defaults, *deps-images]
    steps:
      - attach_workspace:
          at: '/go/src'  
      - run: 
          name: Release package to github
          command: |
            .circleci/github-release.sh
      - store_artifacts:
          path: './artifacts'
          destination: '.'
              
workflows:
  version: 2
  build_and_release:
    jobs:
      - 'deps':
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/                
      - 'test':
          requires:
            - 'deps'
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
      - 'release':
          requires:
            - 'test'
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
