---
defaults:
  defaults: &defaults
    working_directory: '/go/src/github.com/influxdata/telegraf'
  go-1_9: &go-1_9
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.9.7'
  go-1_10: &go-1_10
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.10.3'

version: 2

defaults: &defaults
  docker:
    - image: 'circleci/golang:1.9'
  working_directory: '/go/src/github.com/influxdata/telegraf'

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-{{ .Branch }}-{{ checksum "Godeps" }}         
      - run: 
          name: Sync submodule
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run: 
          name: Install go vendor
          command: |
            make deps
      - run: 
          name: Run test-ci
          command: |
            make test-ci
      - run: 
          name: Build test
          command: |
            CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o build/telegraf cmd/telegraf/telegraf.go
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Godeps" }}
          paths:
            - "/go/pkg"       
          key: vendor-{{ checksum "Gopkg.lock" }}
      - run: 'make deps'
      - save_cache:
          name: 'vendored deps'
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - './vendor'
      - persist_to_workspace:
          root: '/go/src'
          paths:
            - '*'

  test-go-1.9:
    <<: [ *defaults, *go-1_9 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make check'
      - run: 'make test'
  test-go-1.10:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make check'
      - run: 'make test'
  test-go-1.10-386:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'GOARCH=386 make check'
      - run: 'GOARCH=386 make test'

  package:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make package'
      - store_artifacts:
          path: './build'
          destination: 'build'
  release:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Sync submodule
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - restore_cache:
          keys: 
            - v1-{{ .Branch }}-{{ checksum "Godeps" }}                   
      - run: 
          name: Install go vendor
          command: |
            make deps  
      - run: 
          name: Release package to github
          command: |
            .circleci/github-release.sh
      - store_artifacts:
          path: './artifacts'
          destination: '.'
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Godeps" }}
          paths:
            - "/go/pkg"                
      - attach_workspace:
          at: '/go/src'
      - run: 'make package-release'
      - store_artifacts:
          path: './build'
          destination: 'build'
  nightly:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make package-nightly'
      - store_artifacts:
          path: './build'
          destination: 'build'

workflows:
  version: 2
  check:
    jobs:
      - 'build':
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
      - 'release':
          requires:
            - 'build'
      - 'deps':
          filters:
            tags:
              only: /.*/
      - 'test-go-1.9':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-1.10':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-1.10-386':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'package':
          requires:
            - 'test-go-1.9'
            - 'test-go-1.10'
            - 'test-go-1.10-386'
      - 'release':
          requires:
            - 'test-go-1.9'
            - 'test-go-1.10'
            - 'test-go-1.10-386'
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
  nightly:
    jobs:
      - 'deps'
      - 'test-go-1.9':
          requires:
            - 'deps'
      - 'test-go-1.10':
          requires:
            - 'deps'
      - 'test-go-1.10-386':
          requires:
            - 'deps'
      - 'nightly':
          requires:
            - 'test-go-1.9'
            - 'test-go-1.10'
            - 'test-go-1.10-386'
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
