---
defaults: &defaults
  docker:
    - image: 'circleci/golang:1.9.4'
  working_directory: '/go/src/github.com/influxdata/telegraf'
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-{{ .Branch }}-{{ checksum "Godeps" }}         
      - run: 
          name: Sync submodule
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run: 
          name: Install go vendor
          command: |
            make deps
      - run: 
          name: Run test-ci
          command: |
            make test-ci
      - run: 
          name: Build test
          commmand: |
            CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o build/telegraf cmd/telegraf/telegraf.go
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Godeps" }}
          paths:
            - "/go/pkg"       
  release:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Sync submodule
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - restore_cache:
          keys: 
            - v1-{{ .Branch }}-{{ checksum "Godeps" }}                   
      - run: 
          name: Install go vendor
          command: |
            make deps  
      - run: 
          name: Release package to github
          command: |
            .circleci/github-release.sh
      - store_artifacts:
          path: './artifacts'
          destination: '.'
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Godeps" }}
          paths:
            - "/go/pkg"                
workflows:
  version: 2
  build_and_release:
    jobs:
      - 'build':
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
      - 'release':
          requires:
            - 'build'
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/

